name: Create and publish a Container image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version tag from git tag
        id: version_tag
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [[ -n "$TAG_NAME" ]]; then
            echo "version_tag=$TAG_NAME" >> $GITHUB_ENV
          fi

      - name: Generate branch name and commit hash tag
        id: branch_commit_tag
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-} # Replace '/' with '-'
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "branch_commit_tag=${BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.version_tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.branch_commit_tag }}
